### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by pex9** [yannvillellas/polito-se2-24-20-Kiruna-eXplorer#96]
Dear Team Members (Team 20),

As discussed in Demo 3, we have identified a few issues that could be addressed to improve the platform:

Add the option for users to access the platform as visitors, with the ability to view the list of documents.
Enable a way to view a list of document connections, including the associated names, directly in the document card.
Consider renaming "multiple files" to "multiple resources" to make it more intuitive and user-friendly.
Best regards,
Team 17

**Comment by kurtoglusefa** [comment]
Dear Team 20,

I wanted to drop my opinions and suggestions during the Demo 3 but as we ran out of time last week I couldn't.
By asking the professor I am leaving my observations here.
- The document cards do not align with the color pattern used in the main map view.
- The edges of the fields in the "Add Document" modal appear inconsistent. 
- Buttons are not aligned or consistent in terms of the graphical user interface
- On the DocumentPage, the title styling is inconsistent; it is black and does not align with the other text colors.

I wish you the best for the rest of the project and happy new year.

Kind regards,
Team 17
